### ISSUE TITLE
consultar_servidor

### ISSUE THREAD

**Issue by Marcelo-Kyan** [marcydoty/Recursos-NFE-em-Python#11]
Oi Marcilene,

Ao consultar servidor, retorna erro
Estou testando da seguinte maneira

#!/usr/bin/env python
import nfe

i = nfe.nf_e.nf_e()
c = i.extrair_certificado_a1("meucertificado.pfx","minhasenha")
cert = c['cert']
key = c['key']

versao= '3.10'
ambiente = 2
estado = 'SP'
contingencia = False
resp = i.consultar_servidor(cert, key, versao, ambiente, estado, contingencia)

me retorna o seguinte erro:
Traceback (most recent call last):
  File "./teste1.py", line 16, in <module>
    resp = i.consultar_servidor(cert,key,versao,ambiente,estado,contingencia)
  File "/usr/lib/python2.7/site-packages/python_nfe-3.8-py2.7.egg/nfe/nf_e.py", line 70, in consultar_servidor
    status = processo.resposta.cStat.valor
AttributeError: 'tuple' object has no attribute 'resposta'

**Comment by marcydoty** [comment]
Oi Marcelo, desculpa a demora, estou viajando
Vc viu o que retorna somente no processo?
A consulta de servidor é chamada automaticamente antes de enviar a nota. Vc
tentou processar uma nf-e?
Em 9 de abr de 2016 11:39 AM, "Marcelo Kumruyan" <notifications@github.com>
escreveu:

**Comment by Marcelo-Kyan** [comment]
Oi,
Não tentei enviar a nota ainda, mas o retorno que tenho nessa função é um xml.
Esse processo que estou utilizando está correto?, ou seja, o modo do import e as chamadas de funcões?

Seque abaixo o retorno:
nfe versao... 3.10
conectando ao servico SEFAZ.........
servidor homologacao.nfe.fazenda.sp.gov.br
STATUS________________________________________- <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>403 - Forbidden: Access is denied.</title>
<style type="text/css">

</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>403 - Forbidden: Access is denied.</h2>
  <h3>You do not have permission to view this directory or page using the credentials that you supplied.</h3>
 </fieldset></div>
</div>
</body>
</html>

**Comment by marcydoty** [comment]
Está correto sim, só a consulta do servidor que eu não uso, pq eh feita de
forma automática quando vc envia uma Nf-e.  Quanto ao erro, parece que o
endereço de homologação para o estado de são Paulo não funciona mais, como
faz um tempo q não atualizo talvez o endereço de homologação para SP , pode
ter mudado, então tem q mudar na lib também. Vou verificar isso na segunda,
pois do celular, vai ser tenso eu alterar, ok?
Em 9 de abr de 2016 12:26 PM, "Marcelo Kumruyan" <notifications@github.com>
escreveu:

**Comment by Marcelo-Kyan** [comment]
Muito obrigado pela sua atenção, continuarei com os testes, vou tentar emitir uma nota.

**Comment by marcydoty** [comment]
Disponha. :)
Em 9 de abr de 2016 12:38 PM, "Marcelo Kumruyan" <notifications@github.com>
escreveu:

**Comment by Marcelo-Kyan** [comment]
Eu enviei a nota, mas me retorna:
status_resposta '239'
status_motivo 'Rejeição: Cabeçalho - Versão do arquivo XML não suportada'
Verifiquei que em envio está ver versao="3.10"
mas em resposta volta versao="2.00" 

O processo foi o seguinte:
import nfe
i = nfe.nf_e.nf_e()
c = i.extrair_certificado_a1('meucertificado.pfx','minhasenha')
cert = c['cert']
kyan = c['key']
versao = '3.10'
ambiente = 2
estado = 'SP'
contingencia = False
arq = file('nfe.xml','rb')
resposta = i.processar_nfe(arq, cert, key, versao, ambiente, estado, contingencia)




Você tem alguma idéia do que pode ser?

Segue o xml enviado:


[nfe.zip](https://github.com/marcydoty/Recursos-NFE-em-Python/files/211352/nfe.zip)

**Comment by marcydoty** [comment]
O erro parece ser referente a versão do cabeçalho  é não da nota fiscal.
Vou dar uma olhada no seu arquivo.
Em 9 de abr de 2016 1:58 PM, "Marcelo Kumruyan" <notifications@github.com>
escreveu:

**Comment by marcydoty** [comment]
Oi Marcelo, não deu pra eu abrir seu arquivo no celular. Segunda estarei de
volta, e verifico no meu notebook.
Em 9 de abr de 2016 2:01 PM, "Marcilene Ribeiro" <mrasistemas@gmail.com>
escreveu:

**Comment by Marcelo-Kyan** [comment]
Bom dia Marcilene,

Você tem condições de me mandar “manual” de utilização dessa lib?
Pode ser até alguns exemplos de como você envia uma NFe utilizando a lib:
Desde a importação da lib, criação de intancias, emissão e verificação se deu tudo OK.

marcelo

**Comment by marcydoty** [comment]
Oi Marcelo, estou fazendo um lançamento de projeto hoje, infelizmente não
pude responder, mas assim que possível lhe respondo direito, blz?
Manual, eu não tenho, vou ter que montar um exemplo pra vc. Assim que
possível farei isso. Hoje no meu trabalho tenho muito solicitações por
causa do lançamento de um projeto.
Em 11 de abr de 2016 10:20 AM, "Marcelo Kumruyan" <notifications@github.com>
escreveu:

**Comment by Marcelo-Kyan** [comment]
Bom dia Marcilene,

Você consegue alguma documentação da lib Recursos-NFE-em-Python?
Pode ser até exemplos de chamadas das funções em linha de comando em Python.
Estou tentando utilizar esta lib mas não dá certo.
Se não der para você me mandar nada, me avise que eu tento outra solução.
Desde já muito obrigado pela sua atenção.

Marcelo
