### ISSUE TITLE
Baixar xml de nfe emitidas para um determinado cnpj

### ISSUE THREAD

**Issue by adrianobalani** [marcydoty/Recursos-NFE-em-Python#15]
Oi Marcilene gostei muito do seu projeto, está muito bem escrito e bem organizado.
Gostaria de saber se a sua Lib, possibilita baixar xml de nfe emitidas para um cnpj, sem precisar informar a chave da nfe. No caso montaria um script que consulta os servidores e baixa todos os xml's que estão lá.

Mais uma vez, parabens pelo projeto!

Adriano R. Balani

**Comment by marcydoty** [comment]
Oi Adriano, obrigada e desculpe a demora. 
Na lib ainda não tem esta funcionalidade, estou querendo colocar mais a frente.
Abraços,
