### ISSUE TITLE
Não consigo gerar uma assinatura válida

### ISSUE THREAD

**Issue by fpwanderley** [marcydoty/Recursos-NFE-em-Python#8]
Olá Marcilene,

Utilizando a ferramenta, não consegui encontrar como assinar meu XML. Você poderia entrar em contato comigo por email?

fpwanderley@gmail.com

Atenciosamente,
Felipe Wanderley.

**Comment by marcydoty** [comment]
Oi Felipe, tudo bem?

Tente usar o método processar_nfe, pois ele já faz o processo de assinatura
dentro dele.

Abraços,

Em 24 de agosto de 2015 14:06, Felipe Wanderley <notifications@github.com>
escreveu:

> Olá Marcilene,
>
> Utilizando a ferramenta, não consegui encontrar como assinar meu XML. Você
> poderia entrar em contato comigo por email?
>
> fpwanderley@gmail.com
>
> Atenciosamente,
> Felipe Wanderley.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/marcydoty/Recursos-NFE-em-Python/issues/8>.
>



-- 
Atenciosamente,

Marcilene Ribeiro.

**Comment by fpwanderley** [comment]
Olá Marcilene,

Tentei entrar em contato contigo pelo LinkedIn, mas não consegui. Ainda bem
que você me respondeu o email, pois já estou hà 7 dias trabalhando somente
na tentando resolver a assinatura do XML da NFe aqui no trabalho.

Existe alguma jogada na criação do Digest e da assinatura? Venho tentando
utilizar varias bibliotecas para gerar o Digest, e utilizando todo o
conteudo dentro da tag <infNFe>, mas nenhuma delas deu certo. Ja estava
desistindo. Vou tentar utilizar sua lib. Muito obrigado.

Abraco.


Em 25 de agosto de 2015 10:41, Marcilene Ribeiro <notifications@github.com>
escreveu:

**Comment by marcydoty** [comment]
Blz, qualquer dúvida me avisa.

Abraços,

Em 25 de agosto de 2015 10:47, Felipe Wanderley <notifications@github.com>
escreveu:

> Olá Marcilene,
>
> Tentei entrar em contato contigo pelo LinkedIn, mas não consegui. Ainda bem
> que você me respondeu o email, pois já estou hà 7 dias trabalhando somente
> na tentando resolver a assinatura do XML da NFe aqui no trabalho.
>
> Existe alguma jogada na criação do Digest e da assinatura? Venho tentando
> utilizar varias bibliotecas para gerar o Digest, e utilizando todo o
> conteudo dentro da tag <infNFe>, mas nenhuma delas deu certo. Ja estava
> desistindo. Vou tentar utilizar sua lib. Muito obrigado.
>
> Abraco.
>
>
> Em 25 de agosto de 2015 10:41, Marcilene Ribeiro <notifications@github.com
> >
> escreveu:
>
> > Oi Felipe, tudo bem?
> >
> > Tente usar o método processar_nfe, pois ele já faz o processo de
> assinatura
> > dentro dele.
> >
> > Abraços,
> >
> > Em 24 de agosto de 2015 14:06, Felipe Wanderley <
> notifications@github.com>
> > escreveu:
> >
> > > Olá Marcilene,
> > >
> > > Utilizando a ferramenta, não consegui encontrar como assinar meu XML.
> > Você
> > > poderia entrar em contato comigo por email?
> > >
> > > fpwanderley@gmail.com
> > >
> > > Atenciosamente,
> > > Felipe Wanderley.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/marcydoty/Recursos-NFE-em-Python/issues/8>.
> > >
> >
> >
> >
> > --
> > Atenciosamente,
> >
> > Marcilene Ribeiro.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/marcydoty/Recursos-NFE-em-Python/issues/8#issuecomment-134589991
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/marcydoty/Recursos-NFE-em-Python/issues/8#issuecomment-134591397>
> .
>



-- 
Atenciosamente,

Marcilene Ribeiro.

**Comment by fpwanderley** [comment]
Marcilene,

Sem querer ser chato, ja sendo...   Eu to procurando no codigo, somente o
trecho onde acontece a *Assinatura* do XML da NFe. Na verdade, esse eh o
unico trecho de meu interesse na biblioteca por enquanto.

Se voce tiver um tempo, poderia me apontar onde encontrar esse trecho?

Abracos
Felipe Wanderley.

Em 25 de agosto de 2015 10:49, Marcilene Ribeiro <notifications@github.com>
escreveu:

**Comment by marcydoty** [comment]
Oi Felipe,

O trecho que vc quer encontra-se neste arquivo
https://github.com/marcydoty/Recursos-NFE-em-Python/blob/master/nfe/pysped/xml_sped/certificado.py,
 na linha 236, o nome da função é* assina_xml.*

Abraços,

Em 25 de agosto de 2015 17:22, Felipe Wanderley <notifications@github.com>
escreveu:

> Marcilene,
>
> Sem querer ser chato, ja sendo... Eu to procurando no codigo, somente o
> trecho onde acontece a *Assinatura* do XML da NFe. Na verdade, esse eh o
> unico trecho de meu interesse na biblioteca por enquanto.
>
> Se voce tiver um tempo, poderia me apontar onde encontrar esse trecho?
>
> Abracos
> Felipe Wanderley.
>
> Em 25 de agosto de 2015 10:49, Marcilene Ribeiro <notifications@github.com
> >
> escreveu:
>
>
> > Blz, qualquer dúvida me avisa.
> >
> > Abraços,
> >
> > Em 25 de agosto de 2015 10:47, Felipe Wanderley <
> notifications@github.com>
> >
> > escreveu:
> >
> > > Olá Marcilene,
> > >
> > > Tentei entrar em contato contigo pelo LinkedIn, mas não consegui. Ainda
> > bem
> > > que você me respondeu o email, pois já estou hà 7 dias trabalhando
> > somente
> > > na tentando resolver a assinatura do XML da NFe aqui no trabalho.
> > >
> > > Existe alguma jogada na criação do Digest e da assinatura? Venho
> tentando
> > > utilizar varias bibliotecas para gerar o Digest, e utilizando todo o
> > > conteudo dentro da tag <infNFe>, mas nenhuma delas deu certo. Ja estava
> > > desistindo. Vou tentar utilizar sua lib. Muito obrigado.
> > >
> > > Abraco.
> > >
> > >
> > > Em 25 de agosto de 2015 10:41, Marcilene Ribeiro <
> > notifications@github.com
> > > >
> > > escreveu:
> > >
> > > > Oi Felipe, tudo bem?
> > > >
> > > > Tente usar o método processar_nfe, pois ele já faz o processo de
> > > assinatura
> > > > dentro dele.
> > > >
> > > > Abraços,
> > > >
> > > > Em 24 de agosto de 2015 14:06, Felipe Wanderley <
> > > notifications@github.com>
> > > > escreveu:
> > > >
> > > > > Olá Marcilene,
> > > > >
> > > > > Utilizando a ferramenta, não consegui encontrar como assinar meu
> XML.
> > > > Você
> > > > > poderia entrar em contato comigo por email?
> > > > >
> > > > > fpwanderley@gmail.com
> > > > >
> > > > > Atenciosamente,
> > > > > Felipe Wanderley.
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <https://github.com/marcydoty/Recursos-NFE-em-Python/issues/8>.
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > Atenciosamente,
> > > >
> > > > Marcilene Ribeiro.
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > >
> >
> https://github.com/marcydoty/Recursos-NFE-em-Python/issues/8#issuecomment-134589991
> > > >
> > >
> > > > .
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/marcydoty/Recursos-NFE-em-Python/issues/8#issuecomment-134591397
> > >
> >
> > > .
> > >
> >
> >
> >
> > --
> > Atenciosamente,
> >
> > Marcilene Ribeiro.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/marcydoty/Recursos-NFE-em-Python/issues/8#issuecomment-134592204
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/marcydoty/Recursos-NFE-em-Python/issues/8#issuecomment-134728234>
> .
>



-- 
Atenciosamente,

Marcilene Ribeiro.

**Comment by fpwanderley** [comment]
Ola Marcilene!

Tudo certo com a assinatura. Muito obrigado mesmo! Tudo de bom pra voce.

PS: Vou te adicionar no LinkedIn. Espero que nao tenha problema.

Abraco.
Felipe Wanderley.

Em 25 de agosto de 2015 17:31, Marcilene Ribeiro <notifications@github.com>
escreveu:

**Comment by marcydoty** [comment]
Oi Felipe, que bom, fico muito feliz. :D
Pode me adicionar lá.

Abraços,

Em 26 de agosto de 2015 11:22, Felipe Wanderley <notifications@github.com>
escreveu:

> Ola Marcilene!
>
> Tudo certo com a assinatura. Muito obrigado mesmo! Tudo de bom pra voce.
>
> PS: Vou te adicionar no LinkedIn. Espero que nao tenha problema.
>
> Abraco.
> Felipe Wanderley.
>
> Em 25 de agosto de 2015 17:31, Marcilene Ribeiro <notifications@github.com
> >
> escreveu:
>
> > Oi Felipe,
> >
> > O trecho que vc quer encontra-se neste arquivo
> >
> >
> https://github.com/marcydoty/Recursos-NFE-em-Python/blob/master/nfe/pysped/xml_sped/certificado.py
> > ,
> > na linha 236, o nome da função é* assina_xml.*
>
> >
> > Abraços,
> >
> > Em 25 de agosto de 2015 17:22, Felipe Wanderley <
> notifications@github.com>
> > escreveu:
> >
> > > Marcilene,
> > >
> > > Sem querer ser chato, ja sendo... Eu to procurando no codigo, somente o
> > > trecho onde acontece a *Assinatura* do XML da NFe. Na verdade, esse eh
> o
> >
> > > unico trecho de meu interesse na biblioteca por enquanto.
> > >
> > > Se voce tiver um tempo, poderia me apontar onde encontrar esse trecho?
> > >
> > > Abracos
> > > Felipe Wanderley.
> > >
> > > Em 25 de agosto de 2015 10:49, Marcilene Ribeiro <
> > notifications@github.com
> > > >
> > > escreveu:
> > >
> > >
> > > > Blz, qualquer dúvida me avisa.
> > > >
> > > > Abraços,
> > > >
> > > > Em 25 de agosto de 2015 10:47, Felipe Wanderley <
> > > notifications@github.com>
> > > >
> > > > escreveu:
> > > >
> > > > > Olá Marcilene,
> > > > >
> > > > > Tentei entrar em contato contigo pelo LinkedIn, mas não consegui.
> > Ainda
> > > > bem
> > > > > que você me respondeu o email, pois já estou hà 7 dias trabalhando
> > > > somente
> > > > > na tentando resolver a assinatura do XML da NFe aqui no trabalho.
> > > > >
> > > > > Existe alguma jogada na criação do Digest e da assinatura? Venho
> > > tentando
> > > > > utilizar varias bibliotecas para gerar o Digest, e utilizando todo
> o
> > > > > conteudo dentro da tag <infNFe>, mas nenhuma delas deu certo. Ja
> > estava
> > > > > desistindo. Vou tentar utilizar sua lib. Muito obrigado.
> > > > >
> > > > > Abraco.
> > > > >
> > > > >
> > > > > Em 25 de agosto de 2015 10:41, Marcilene Ribeiro <
> > > > notifications@github.com
> > > > > >
> > > > > escreveu:
> > > > >
> > > > > > Oi Felipe, tudo bem?
> > > > > >
> > > > > > Tente usar o método processar_nfe, pois ele já faz o processo de
> > > > > assinatura
> > > > > > dentro dele.
> > > > > >
> > > > > > Abraços,
> > > > > >
> > > > > > Em 24 de agosto de 2015 14:06, Felipe Wanderley <
> > > > > notifications@github.com>
> > > > > > escreveu:
> > > > > >
> > > > > > > Olá Marcilene,
> > > > > > >
> > > > > > > Utilizando a ferramenta, não consegui encontrar como assinar
> meu
> > > XML.
> > > > > > Você
> > > > > > > poderia entrar em contato comigo por email?
> > > > > > >
> > > > > > > fpwanderley@gmail.com
> > > > > > >
> > > > > > > Atenciosamente,
> > > > > > > Felipe Wanderley.
> > > > > > >
> > > > > > > —
> > > > > > > Reply to this email directly or view it on GitHub
> > > > > > > <https://github.com/marcydoty/Recursos-NFE-em-Python/issues/8
> >.
> > > > > > >
> > > > > >
> > > > > >
> > > > > >
> > > > > > --
> > > > > > Atenciosamente,
> > > > > >
> > > > > > Marcilene Ribeiro.
> > > > > >
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > > <
> > > > >
> > > >
> > >
> >
> https://github.com/marcydoty/Recursos-NFE-em-Python/issues/8#issuecomment-134589991
> > > > > >
> > > > >
> > > > > > .
> > > > > >
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > > >
> > >
> >
> https://github.com/marcydoty/Recursos-NFE-em-Python/issues/8#issuecomment-134591397
> > > > >
> > > >
> > > > > .
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > Atenciosamente,
> > > >
> > > > Marcilene Ribeiro.
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > >
> >
> https://github.com/marcydoty/Recursos-NFE-em-Python/issues/8#issuecomment-134592204
> > > >
> > >
> > > > .
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/marcydoty/Recursos-NFE-em-Python/issues/8#issuecomment-134728234
> > >
> >
> > > .
> > >
> >
> >
> >
> > --
> > Atenciosamente,
> >
> > Marcilene Ribeiro.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/marcydoty/Recursos-NFE-em-Python/issues/8#issuecomment-134731514
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/marcydoty/Recursos-NFE-em-Python/issues/8#issuecomment-135038076>
> .
>



-- 
Atenciosamente,

Marcilene Ribeiro.

**Comment by Marcelo-Kyan** [comment]
Marcilene, estou escrevendo só para parabenizá-la pelo seu trabalho.
Dei uma olhada por cima e achei maravilhoso.
Hoje vou começar a estudá-lo e tentar implementá-lo em minha aplicação.
O PYTHON precisa de pessoas como você.

**Comment by Marcelo-Kyan** [comment]
Oi Marcilene, funciona para São Paulo?

**Comment by marcydoty** [comment]
Oi Marcelo, obrigada. :D
 Sim, tem várias pessoas de São Paulo que utilizam a lib.
Só não sei se falta alguma atualização para SP, mas vou verificar.


2016-04-08 10:28 GMT-03:00 Marcelo Kumruyan <notifications@github.com>:

> Oi Marcilene, funciona para São Paulo?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/marcydoty/Recursos-NFE-em-Python/issues/8#issuecomment-207432371>
>



-- 
Atenciosamente,

Marcilene Ribeiro.


"Quanto melhor é adquirir a sabedoria do que o ouro! E mais excelente,
adquirir a prudência do que a prata!" Provérbios 16:16

**Comment by Marcelo-Kyan** [comment]
Oi Marcilene, Conseguí só agora ajeitar meu ambiente e instalar sua lib.
Estou chamando o python em linha de comando para testar algumas funcionalidades.
Estou tentando extrair o certificado a1 mas não estou conseguindo.
Voce poderia me mandar como posso acessar a função para este proposito?
Na linha de comando em python, só para me dar um caminho para que eu possa continuar os testes.
Obrigado
