### ISSUE TITLE
Geração de DANFE

### ISSUE THREAD

**Issue by Sjasilva** [marcydoty/Recursos-NFE-em-Python#9]
Olá Marcilene, tudo bem?

Estou tentando gerar um DANFE utilizando o método gerar_danfe. Porém ocorreram alguns erros relacionados a string do xml que estou utilizando. Nas tentativas de contornar o erro, o máximo que consegui gerar foi um arquivo .pdf em branco com algumas informaçoes como titulo, PDFlibrary , etc.

Gostaria de saber qual xml devo utilizar para conseguir gerar um DANFE.pdf.
Qual parte do Código você faz as atribuições do xml para o que será enviado para o arquivo.

Abraço.

**Comment by marcydoty** [comment]
Oi Saulo, tudo bem?

O XML que vc deve enviar , é o XML de uma NF-e já autorizada. No método gerar_danfe vc deve passar no parâmetro nfe somente a String desta nota autorizada.

Abraços,
